name: Deploy Dotnet App with Docker Compose (Multiple Services)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test SSH Connection
        env:
          SERVER_USER: ubuntu
          SERVER_IP: 51.20.167.66
        run: |
          echo "Testing SSH connection to server using username 'ubuntu'"
          sshpass -p "qwerty" ssh -o StrictHostKeyChecking=no ubuntu@51.20.167.66 -p 22 "echo 'Connected as $(whoami)'"

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 51.20.167.66
          username: ubuntu
          password: qwerty
          debug: true

          script: |
            cd /home/ubuntu/driveC/carApi/
            git pull origin main
            docker-compose pull  # Pull the latest images for all services
            docker-compose down  # Stop and remove the current containers
            docker-compose up -d --build
